# tasks file for pycharm
---
- debug:
    msg: "{{pycharm_download_directory_group}}"
- name: Create (download) directory
  file:
    path: "{{ pycharm_downloads_path }}"
    state: directory
    mode: 0775
    group: "{{ pycharm_download_directory_group }}"
  become: true
  tags:
    - configuration
    - pycharm
    - pycharm-download

- name: Find latest version
  uri:
    url: "http://data.services.jetbrains.com/products/releases?code=PCP%2CPCC&latest=true&type=release"
    return_content: yes
    body_format: json
  register: releases_response
  when: pycharm_version == 'latest'

- name: "Set pycharm_version to latest community version (if edition==community)"
  set_fact:
    pycharm_version: "{{ releases_response.json.PCC.0.version }}"
  when: pycharm_version == 'latest' and pycharm_edition == 'community'

- name: "Set pycharm_version to latest professional version (if edition==professional)"
  set_fact:
    pycharm_version: "{{ releases_response.json.PCP.0.version }}"
  when: pycharm_version == 'latest' and pycharm_edition == 'professional'

- name: Download
  get_url:
    url: "http://download.jetbrains.com/python/pycharm-{{ pycharm_edition }}-{{ pycharm_version }}.tar.gz"
    dest: "{{ pycharm_downloads_path }}/pycharm-{{ pycharm_edition }}-{{ pycharm_version }}.tar.gz"
    mode: 0755
  tags:
    - configuration
    - pycharm
    - pycharm-downloads

- name: Install
  unarchive:
    src: "{{ pycharm_downloads_path }}/pycharm-{{ pycharm_edition }}-{{ pycharm_version }}.tar.gz"
    dest: "{{ pycharm_install_prefix }}"
    creates: "{{ pycharm_install_prefix }}/pycharm-{{ pycharm_version }}"
    copy: false
  become: true
  tags:
    - configuration
    - pycharm
    - pycharm-install

- name: Ensure pycharm bin exist
  template:
    src: pycharm.j2
    dest: /usr/local/bin/pycharm
    mode: 0755
  become: true

- name: Ensure pycharm shortcut is present
  template: 
    src: pycharm.desktop.j2
    dest: /usr/share/applications/pycharm.desktop
    mode: 0755
  become: true
